[package]
name = "boda"
version = "0.1.0"
edition = "2024"
repository = "https://git.sr.ht/~beleap/boda"
description = "opinionated alternative watch"
license-file = "LICENSE"

[dependencies]
crossbeam-channel = "0.5.15"
ctrlc = "3.4.6"
crossterm = "0.29.0"
clap = { version = "4.5.37", features = ["derive"] }
chrono = "0.4.40"
